twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes:
        - 'bootstrap_3_horizontal_layout.html.twig'
        - "@NinesUtil/form/fields.html.twig"
        - '@TetranzSelect2Entity/Form/fields.html.twig'
        - 'jquery.collection.html.twig'
