nines_blog:
  type: annotation
  prefix: /blog
  resource: '@NinesBlogBundle/Controller'

nines_dc:
  type: annotation
  prefix: /dublin_core
  resource: '@NinesDublinCoreBundle/Controller'

nines_editor:
  type: annotation
  prefix: /editor
  resource: '@NinesEditorBundle/Controller'

nines_feedback:
  type: annotation
  prefix: /feedback
  resource: '@NinesFeedbackBundle/Controller'

nines_media:
  type: annotation
  prefix: /media
  resource: '@NinesMediaBundle/Controller'

nines_user:
  resource: '@NinesUserBundle/Resources/config/routes.yaml'

nines_util:
  type: annotation
  prefix: /util
  resource: '@NinesUtilBundle/Controller'
